export const CHAPTER_CONTENT = [
  { id: 'hero', eyebrow: 'Zero-knowledge object storage', headline: 'Your files become noise.', body: 'ShardX obfuscates every upload with a ChaCha20 noise stream, splits it into shards and stores them under your own KMS key. The only thing that can put them back together is a key file that never leaves your device.', pills: ['AWS S3 · KMS · DynamoDB', 'Go + React', 'MIT'] },
  { id: 'upload', eyebrow: '01 / Upload', headline: 'Streamed in 5 MB chunks.', body: 'Your browser opens an upload session and streams the file chunk by chunk. Pause, resume or cancel at any time — a failed chunk retries with exponential backoff, never from zero.', pills: ['5 MB chunks', 'pause / resume', 'retry with backoff'] },
  { id: 'obfuscate', eyebrow: '02 / Obfuscate', headline: 'ChaCha20 noise, everywhere.', body: 'A 32-byte seed initialises a ChaCha20-DRBG. Deterministic noise is injected at calculated offsets throughout the file. What reaches the bucket is statistically indistinguishable from random bytes.', pills: ['32-byte seed', 'ChaCha20-DRBG', 'deterministic offsets'] },
  { id: 'shard', eyebrow: '03 / Shard', headline: 'Split by strategy.', body: 'The obfuscated stream is cut into shards using the strategy you pick — balanced, greedy, proportional or manual. Preview the plan before you commit.', pills: ['balanced', 'greedy', 'proportional', 'manual'] },
  { id: 'store', eyebrow: '04 / Store', headline: 'S3, under your KMS key.', body: 'Each shard is written to S3 with SSE-KMS using a customer-managed key. Its SHA-256, size and location are recorded in DynamoDB. A shard that fails is queued to SQS and retried by a worker — you never have to re-upload.', pills: ['SSE-KMS CMK', 'DynamoDB shard records', 'SQS retry + DLQ'] },
  { id: 'keyfile', eyebrow: '05 / Key file', headline: 'The server never sees the seed.', body: 'The seed and the chunk map exist only in your .2xpfm.key file. A full compromise of the bucket and the database yields nothing readable. Keep it safe; it is the only way back.', pills: ['.2xpfm.key', 'client-only', 'seed + chunk map'] },
  { id: 'integrity', eyebrow: '06 / Integrity', headline: 'Every shard, verified.', body: 'The Integrity Engine scores each file, maps where every shard lives and records an audit timeline of every lifecycle event — straight from DynamoDB and EventBridge.', pills: ['health score', 'shard map', 'audit timeline'] },
  { id: 'drive', eyebrow: '07 / Drive mode', headline: 'No AWS? Use Drive.', body: 'The same pipeline can shard a file across several linked Google Drive accounts. Three free accounts give you 45 GB of zero-knowledge storage without a cloud bill.', pills: ['3 × 15 GB', 'OAuth linking', 'same pipeline'] },
  { id: 'cta', eyebrow: 'Begin', headline: 'Create your vault.', body: 'Sign up, drop a file, download your key. Read the guide if you want the whole story first.', pills: [] },
] as const;
